openapi: "3.0.1"
info:
  title: Doockeep clients microservice
  version: "1.0"
servers:
  - url: "http://dockeep-clients-ms-elb-690144778.us-east-2.elb.amazonaws.com"
paths:
  /apigateway:
    get:
      responses:
        "200":
          description: Respuesta exitosa
      x-amazon-apigateway-integration:
        type: http_proxy
        uri: "/apigateway" # Usa "/" si deseas que la solicitud se dirija a la raíz del servidor
        httpMethod: GET
