openapi: "3.0.1"
info:
  title: Doockeep clients microservice
  version: "1.0"
paths:
  /apigateway:
    get:
      responses:
        "200":
          description: Respuesta exitosa
      x-amazon-apigateway-integration:
        type: http_proxy
        uri: "http://dockeep-clients-ms-elb-test-254989589.us-east-2.elb.amazonaws.com/" # Reemplaza con la URL real de tu ELB
        httpMethod: GET
