openapi: "3.0.1"
info:
  title: "clients"
  version: "2023-10-14 14:58:44UTC"
servers:
- url: "https://b556rn7b86.execute-api.us-east-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
paths:
  /apigateway:
    x-amazon-apigateway-any-method:
      responses:
        default:
          description: "Default response for ANY /apigateway"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "1.0"
        type: "http_proxy"
        httpMethod: "GET"
        uri: "http://dockeep-clients-ms-elb-690144778.us-east-2.elb.amazonaws.com/apigateway"
        connectionType: "INTERNET"
x-amazon-apigateway-importexport-version: "1.0"
