openapi: "3.0.1"
info:
  title: "users"
  version: "2023-10-14 14:58:44UTC"
servers:
  - url: "https://b556rn7b86.execute-api.us-east-2.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: ""
paths:
  /users: # Ruta para crear un usuario
    post: # Método POST
      summary: "Crear un usuario"
      requestBody:
        description: "Datos del usuario a crear"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User" # Hacer referencia al esquema del usuario
      responses:
        201:
          description: "Usuario creado exitosamente"
        400:
          description: "Solicitud incorrecta"
        500:
          description: "Error interno del servidor"
      x-amazon-apigateway-integration: # Integración de Amazon
        type: "http_proxy" # Usar http_proxy para apuntar al mismo ELB
        httpMethod: "POST"
        uri: "http://dockeep-clients-ms-elb-690144778.us-east-2.elb.amazonaws.com/api/users"
components:
  schemas:
    User:
      type: "object"
      properties:
        id:
          type: "integer"
        username:
          type: "string"
        email:
          type: "string"
        # Otros campos del usuario
