openapi: 3.0.0
info:
  title: Mi API
  version: 1.0.0
paths:
  /mi-ruta-get:
    get:
      summary: Obtener información
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              example:
                message: "¡Hola, mundo!"
