on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ secrets.AWS_REGION }}

    - name: Build Docker image
      run: |
        docker build -t dockeep-clients-ms .
        docker tag dockeep-clients-ms:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

    - name: Authenticate to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

    - name: Deploy to AWS ECS
      run: |
        aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment
    - name: Deploy CloudFormation Stack
      run: |
        # Nombre de la pila CloudFormation
        stack_name="mi-stack-cloudformation"

        # Nombre del archivo de plantilla CloudFormation (debes crear este archivo)
        template_file="template.yml"

        # Parámetros opcionales para la pila (si es necesario)
        parameters="--parameters ParameterKey=KeyName,ParameterValue=my-key"

        # Crea o actualiza la pila de CloudFormation
        aws cloudformation deploy \
          --stack-name $stack_name \
          --template-file $template_file \
          --parameter-overrides $parameters \
          --capabilities CAPABILITY_IAM

        # Espera hasta que la pila se complete
        aws cloudformation wait stack-create-complete --stack-name $stack_name

        # Obtiene la URL de consumo de la API de CloudFormation (deberías definirla en tu plantilla)
        api_url=$(aws cloudformation describe-stacks --stack-name $stack_name --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' --output text)

        echo "URL de la API: $api_url"

        # Puedes almacenar esta URL en una variable de entorno o usarla como necesites
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

